name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: |
          sudo apt-get update
          sudo npm install

      - name: Secure Copy Files via Bastion Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BASTION_HOST }}  # Public Bastion Host
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "*"
          target: "/var/www/server"
          timeout: "120s"
          proxy_host: ${{ secrets.SERVER_IP }}  # Private EC2
          proxy_username: ${{ secrets.USER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Restart PM2 process
        uses: appleboy/ssh-action@v0.1.7    
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
                  cd /var/www/server
                  pm2 restart all

            
        
