name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: |
          sudo apt-get update
          sudo npm install

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: "./"
           target: "/var/www/sever"
           
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
            cd /var/www/server
            pm2 start server.js 
            pm2 startup 
            pm2 save 
            pm2 restart all 
            
            
