name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: |
          sudo apt-get update
          sudo npm install

      - name: SCP
        run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
        chmod 600 ~/.ssh/aws-key.pem

      - name: Copy files using SSM and SCP
        run: |
        aws ssm start-session --target i-${{ secrets.SERVER_IP }} --document-name AWS-StartSSHSession
        scp -i ~/.ssh/aws-key.pem -r * ec2-user@${{ secrets.SERVER_IP }}:/var/www/server



      - name: Restart PM2 process
        uses: appleboy/ssh-action@v0.1.7    
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
                  cd /var/www/server
                  pm2 restart all

            
        
