name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: |
          sudo apt-get update
          sudo npm install

      - name: Set Up SSH Key for Bastion Host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/bastion_key
          chmod 600 ~/.ssh/bastion_key

      - name: Set Up SSH Key for Private Instance
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/private_instance_key
          chmod 600 ~/.ssh/private_instance_key

      - name: Configure SSH for Bastion Proxy
        run: |
          echo "
          Host bastion
            HostName ${{ secrets.BASTION_HOST }}
            User ${{ secrets.USER }}
            IdentityFile ~/.ssh/bastion_key
          Host private-instance
            HostName ${{ secrets.PRIVATE_INSTANCE_HOST }}
            User ${{ secrets.USER }}
            IdentityFile ~/.ssh/private_instance_key
            ProxyJump bastion
          " > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Copy Files via SCP through Bastion Host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRIVATE_INSTANCE_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          proxy_host: ${{ secrets.BASTION_HOST }}
          proxy_username: ${{ secrets.USER }}
          proxy_key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "/var/www/server"

      - name: Restart Application on Private Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRIVATE_INSTANCE_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          proxy_host: ${{ secrets.BASTION_HOST }}
          proxy_username: ${{ secrets.USER }}
          proxy_key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/server
            sudo pm2 restart all 

            
        
